### PR TITLE
259 nonblocking backend uses a dynamic schedule

### LINKED ISSUE #259: Nonblocking backend uses a dynamic schedule...
... when the loop body under uniform inputs would have a uniform run-time. The overarching ALP principle is to choose a static schedule in such cases instead.

Crossref #250 for other minor issues that could piggy-back on a related MR.

Thanks to Alberto Scolari for detecting the issue.

### PR DESCRIPTION
**Pull request by anyzelman**
Closes issue #259

### CODE REVIEW

**Comment by anyzelman** [comment]
Hi @aristeidis-mastoras @alberto-scolari , this MR should fix the schedule issue in the nonblocking backend. Could you both have a look and review it for anything I might have missed? Many thanks!

**Comment by anyzelman** [comment]
At this point, manual smoke tests and GitHub CI pass

**Comment by anyzelman** [comment]
Also all unit tests when manually fired pass. Waiting internal CI

**Review by aristeidis-mastoras — DISMISSED** [review]
OK

**Comment by anyzelman** [comment]
Tests OK, waiting for a thumbs-up from @aristeidis-mastoras and/or @alberto-scolari

**Review by aristeidis-mastoras — APPROVED** [review]
OK

**Comment by alberto-scolari** [comment]
Looks definitely good to me as well!

**Pull request merged**
